services:
    project-yourcloud.me:
        image: ghcr.io/anantk2243/project_yourcloud_ui:latest
        container_name: project-yourcloud.me
        ports:
            - "4200:4200"
        env_file:
            - .env
        volumes:
            - ./ssl:/app/ssl:ro
        restart: unless-stopped
        networks:
            - yourcloud-network

    cloudflared:
        image: cloudflare/cloudflared:latest
        container_name: yourcloud-tunnel
        command: tunnel --no-autoupdate run
        environment:
            - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
        restart: unless-stopped
        depends_on:
            - project-yourcloud.me
        networks:
            - yourcloud-network

    watchtower:
        image: containrrr/watchtower:latest
        container_name: watchtower
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: --interval 300 project-yourcloud.me
        networks:
            - yourcloud-network

networks:
    yourcloud-network:
        driver: bridge
