services:
  yourcloud-ui:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: yourcloud-ui
    ports:
      - "${FRONTEND_PORT:-4200}:${FRONTEND_PORT:-4200}"
      - "${WS_PORT:-8080}:${WS_PORT:-8080}"
    env_file:
      - .env
    volumes:
      - ./ssl:/app/ssl:ro
    restart: unless-stopped
    networks:
      - yourcloud-network

  # Optional: Cloudflare Tunnel service
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: yourcloud-tunnel
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped
    depends_on:
      - yourcloud-ui
    networks:
      - yourcloud-network
    profiles:
      - tunnel

networks:
  yourcloud-network:
    driver: bridge
